print("==========")
print("ax\u00B2 + bx + c = 0 ")
print("==========")
print("\u25B3 = ? ")
a = input("a = ")
b = input("b = ")
c = input("c = ")
output = int(b)**2 - 4*int(a)*int(c)
print(f" \u25B3 =    {output} ")
